### ISSUE TITLE
Question about rendering

### ISSUE THREAD

**Issue by Hatsune1** [facebookresearch/banmo#22]
Hello,

Thank you for you brilliant job and sharing your code. 

I am trying to run your project on my own computer. Until optimization, it works well under the auto-built environment. But in the rendering process, I met lots of "no mesh found" and error report `No such file or directory: 'logdir/cat-pikachiu-e120-b256-ft3/opts.log'`. 

I can see that the problem is that in the rendering command: `bash scripts/render_mgpu.sh 0 $seqname logdir/$seqname-e120-b256-ft3/params_latest.pth "0 1 2 3 4 5 6 7 8 9 10" 256`, files in the folder with suffix "-ft3" is needed. But only "-ft1" and "-ft2" folder is generated in optimization step, according to template.sh, "-ft3" folder is likely not generated. 

By the way, by searching globally in the whole project, "-ft3" only appears in `scripts/abalations/template-human-noactive.sh` and `scripts/abalations/template-human-nosymm.sh`. Since I haven't understand fully of your code yet, I am not sure when and where I could reach the generation of "ft3" folder. If it is convenience, could you simply explain what is the meaning of "ft"?

Could you please give me some advice on the problem I met now in rendering step? Thank you!

**Comment by gengshan-y** [comment]
Hi, thanks for bringing this up, please check the latest readme files. The ft3 should really be ft2 (due to some recent updates). 

For the meaning of the fine-tuning stages, see [supplement B.3. Multi-stage optimization. ](https://banmo-www.github.io/banmo-cvpr.pdf) 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/13134872/176725018-dbb97a59-3946-4944-b635-4e9cf79c933a.png">

**Comment by Hatsune1** [comment]
Thanks for your answer. :)
