### ISSUE TITLE
CSE embedding for other object categories

### ISSUE THREAD

**Issue by zc-alexfan** [facebookresearch/banmo#26]
Hi, thanks for sharing the code. I really like your work. I want to try BANMO on objects that are neither human nor four-legged animals but it seems like BANMO assumes that. Would the results be degenerative if the CSE embeddings are not pre-trained. I noticed Tab. 5 mentioned "pre-trained embedding" and said the pre-training is not too important as long as the initial pose is good?

**Comment by gengshan-y** [comment]
Hi, based on the results on a few categories we tried (e.g., penguin, laikago robot, eagle, hands, results on [this page](https://banmo-www.github.io/results.html#pgn)), densepose is not that important given good enough initial root pose. 

Also note those cases do not contain challenging self-occlusions caused by articulations. I think some form of correspondence like densepose-cse is still needed for more challenging cases.

**Comment by zc-alexfan** [comment]
Thanks for the quick response! One last question: have you tried on the reconstruction in which the object is occluded more heavily? I am curious in how the method handles occlusion.

**Comment by gengshan-y** [comment]
There are two cases I can think of. For one, if the target is occluded by some other objects/background, the reconstructed shape will be (mistakenly) penalized by the **silhouette reconstruction loss** due to the wrong off-the-shelf segmentations. In this case, banmo would likely fail.

In the second case, if the object is out of the image boundary, banmo should work, since out-of-frame pixels are not sampled to compute losses. However in practice, this may still produce worse results since off-the-shelf segmentation method is usually not robust to partially out-of-frame objects.
