### ISSUE TITLE
Canonical mesh degenerates after epoch 1

### ISSUE THREAD

**Issue by kts707** [facebookresearch/banmo#27]
Hi Gengshan,

Thanks for your great work!

After epoch 1 in the last training stage, I noticed that the canonical mesh always breaks down and needs a few epochs to get back to the correct shape (roughly) again. This happens in the trainings on all the datasets (cat, AMA, etc.). Do you know what causes this effect at epoch 1? Thanks!

For example, these are the canonical meshes after epoch 0 to epoch 3 in the **last training stage** on AMA human dataset (notice that after epoch 1 the mesh degenerates):

![mesh_rest-0](https://user-images.githubusercontent.com/59402345/184700802-28a395f6-b2c4-49cd-8e33-c90e91581ab8.png)
|:--:|
| <b>epoch 0 canonical mesh in last training stage</b>|

![mesh_rest-1](https://user-images.githubusercontent.com/59402345/184701373-2dd09b0b-ce3d-46f8-88f4-5e85b9aa5094.png)
|:--:|
| <b>epoch 1 canonical mesh in last training stage</b>|

![mesh_rest-2](https://user-images.githubusercontent.com/59402345/184701432-26956db8-c790-40c0-87cc-b007c18fcba0.png)
|:--:|
| <b>epoch 2 canonical mesh in last training stage</b>|

![mesh_rest-3](https://user-images.githubusercontent.com/59402345/184701459-43dfe048-8c1a-4112-b9a8-44d21a59ec61.png)
|:--:|
| <b>epoch 3 canonical mesh in last training stage</b>|

**Comment by gengshan-y** [comment]
Hi, this is an expected behavior in the final optimization stage.
It is triggered by the `--reset_beta` parameter [here](https://github.com/facebookresearch/banmo/blob/1d022945be987a601a36a25c27e71a8c06008bef/scripts/template.sh#L57), which resets the "transparency" parameter of the neural sdf.

Adding this will force the shape to be re-optimized at the beginning of the last stage, which helps jumping out of local optima in certain cases.

**Comment by kts707** [comment]
I see. Thanks for the quick response!
