### ISSUE TITLE
Volume rendering

### ISSUE THREAD

**Issue by s0rrymaker77777** [facebookresearch/banmo#50]
Hi, thanks for your code. I want to ask the question about the calculation of sil_coarse in rendering.py 
https://github.com/facebookresearch/banmo/blob/c4498030aeca9b056e700892788025a80953cb5a/nnutils/rendering.py#L359
Why does it need to add [:, :-1] to weights while others do not? Thanks!
https://github.com/facebookresearch/banmo/blob/c4498030aeca9b056e700892788025a80953cb5a/nnutils/rendering.py#L219

**Comment by gengshan-y** [comment]
Hi, this is because the last bin along the sampled ray between the near and far point is set to have infinite length (see [here](https://github.com/facebookresearch/banmo/blob/c4498030aeca9b056e700892788025a80953cb5a/nnutils/rendering.py#L177-L180)). 

You may think about the last bin as the non-object space. When rending the object silhouette, we ignore the last bin. When rendering color, we could either consider the last bin as an ambient color, or ignore it as well.

**Comment by s0rrymaker77777** [comment]
Thank you for the reply.
